name: Compile BootRom

on:
  push:
  pull_request:

jobs:
  building:
    strategy:
      matrix:
        rgbds: ['', '--HEAD']
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install RGBDS
        run: |
          brew install ${{ matrix.rgbds }} rgbds
      - name: Build ROMs
        run: |
          make
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bootrom-${{ matrix.rgbds }}
          path: bin/*.bin
          if-no-files-found: error
